std = "roblox"
exclude = ["external/*", "*.spec.lua", "scripts/*"]

[config]
empty_if = { comments_count = true }

[lints]
parenthese_conditions = "allow"
incorrect_standard_library_use = "warn"
global_usage = "allow"