#!/bin/bash
# zap.sh - Recursively combines multiple .zap files into a single config.zap file
# Can be called from parent directory: scripts/zap.sh
# Or from within scripts directory: ./zap.sh
# Usage: ./zap.sh [--place|-p <place_name>] [--non-interactive]

NON_INTERACTIVE=false
PLACE_NAME="game"  # Default place

# Parse command line arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --non-interactive)
      NON_INTERACTIVE=true
      shift
      ;;
    --place|-p)
      PLACE_NAME="$2"
      shift 2
      ;;
    *)
      echo "Unknown option: $1"
      echo "Usage: $0 [--place|-p <place_name>] [--non-interactive]"
      exit 1
      ;;
  esac
done

# Ensure we're working with the correct paths regardless of where script is called from
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

# Create output directory if it doesn't exist
OUTPUT_DIR="$ROOT_DIR"
mkdir -p "$OUTPUT_DIR"

# Path to output file
OUTPUT_FILE="$OUTPUT_DIR/config.zap"

# Check if place-specific events directory exists, fallback to general events
EVENTS_DIR="$ROOT_DIR/events/$PLACE_NAME"
if [[ ! -d "$EVENTS_DIR" ]]; then
  EVENTS_DIR="$ROOT_DIR/events"
  echo "Place-specific events directory not found, using general events directory: $EVENTS_DIR"
else
  echo "Using place-specific events directory: $EVENTS_DIR"
fi

# Write header configuration to the output file
cat > "$OUTPUT_FILE" << EOF
-- This file is auto-generated by scripts/zap.sh
-- Do not edit this file directly. Edit the source .zap files instead.
opt server_output = "places/$PLACE_NAME/src/Server/zap.luau"
opt client_output = "places/$PLACE_NAME/src/Client/zap.luau"
opt tooling = true
opt tooling_output = "places/$PLACE_NAME/src/Shared/RemoteName.profiler.luau"

EOF

echo "Processing Zap files for place: $PLACE_NAME..."

# Process core.zap first (if it exists)
CORE_FILE="$EVENTS_DIR/core.zap"
if [[ -f "$CORE_FILE" ]]; then
  echo " Adding $CORE_FILE first..."
  cat "$CORE_FILE" >> "$OUTPUT_FILE"
  echo -e "\n" >> "$OUTPUT_FILE"
fi

# Create a temporary file to store the list of all other .zap files
TEMP_FILE=$(mktemp)

# Process $ROOT_DIR/events first (including core.zap)
find "$ROOT_DIR/events" -maxdepth 1 -type f -name "*.zap" >> "$TEMP_FILE"

# Find all .zap files recursively (excluding the already processed core.zap)
find "$EVENTS_DIR" -type f -name "*.zap" | grep -v "core\.zap$" >> "$TEMP_FILE"

# Process each file
while IFS= read -r file; do
  rel_path=${file#"$ROOT_DIR/"}
  echo "  Processing $rel_path..."
  cat "$file" >> "$OUTPUT_FILE"
  echo -e "\n" >> "$OUTPUT_FILE"
done < "$TEMP_FILE"

# Remove the temporary file
rm "$TEMP_FILE"

# Run the zap file
echo "Running Zap file..."
zap "$OUTPUT_FILE"

echo "Combined Zap file created at $OUTPUT_FILE"
echo "Place: $PLACE_NAME"
echo "Events directory: $EVENTS_DIR"
echo "Total size: $(wc -l < "$OUTPUT_FILE") lines"

if [[ -t 0 && "$NON_INTERACTIVE" != "true" ]]; then
  echo "Press Enter to continue..."
  read
fi